spring:
  datasource:
    url: jdbc:h2:mem:orders
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update

kafka:
  bootstrap-servers: localhost:9092
# Application Configuration
