apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: order-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: cloudnativeplayground/inventory-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: order-system
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: inventory-service
