apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: order-system
data:
  zookeeper.connection: zookeeper:2181

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: order-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: order-system
spec:
  ports:
    - port: 2181
  selector:
    app: zookeeper

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: order-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: order-system
spec:
  ports:
    - port: 9092
  selector:
    app: kafka
