apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: order-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: cloudnativeplayground/notification-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"

---

apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: order-system
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: notification-service
