apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: order-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: cloudnativeplayground/payment-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"

---

apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: order-system
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: payment-service
